
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[262] =
    {   0,
        0,    0,   95,   93,   92,    1,   77,   93,   93,   83,
       76,   93,   71,   72,   81,   80,   68,   79,   75,   82,
        9,    9,   69,   65,   84,   70,   85,   88,   91,   73,
       74,   86,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   66,   87,
       67,   78,   26,    0,   17,    0,    0,    0,   31,   67,
       27,   36,    0,    0,   29,   19,   32,   20,   33,   18,
       15,    0,    0,   30,   16,    9,    0,   12,    0,   74,
       66,   73,   21,   23,   25,   24,   22,    0,   91,   37,
       91,   91,   91,   91,   44,   91,   91,   91,   91,   50,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   38,   28,    0,    0,   13,    0,   15,
        0,    0,    0,    0,    2,   10,    0,   16,    0,   14,
       11,   34,   35,   91,   91,   91,   91,   91,   91,   91,
       91,   49,   51,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,    0,
        0,    0,   15,    3,    0,   15,    0,   16,   14,   11,
       39,   91,   41,   91,   91,   91,   46,   91,   91,   52,
       90,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   63,   91,    0,    0,    0,   15,   40,

       42,   91,   91,   91,   48,   91,   91,   91,   89,   55,
       91,   91,   91,   91,   91,   61,   91,   64,    0,    0,
       91,   45,   47,   91,   54,   56,   57,   58,   59,   91,
       91,    0,    0,   91,   91,   60,   91,    0,    0,   43,
       53,   62,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    6,    8,    0,    0,    0,    8,    5,    4,    7,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    7,    7,    8,
        8,    8,    8,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[274] =
    {   0,
        0,    0,  564,  565,  565,  565,  539,   60,   26,   44,
       61,  527,  565,  565,  537,   57,  565,   58,   56,   60,
       79,   60,  535,  565,   82,  535,   62,  565,  552,  565,
      565,  533,   83,   87,   91,   94,   95,   98,  107,  108,
       88,  103,  109,  118,  111,  112,  114,  116,  565,  104,
      565,  565,  565,  113,  565,  553,  513,  504,  565,  565,
      565,  565,  120,  122,  565,  565,  565,  565,  565,  565,
      149,  120,  550,  565,  156,  183,  174,  164,    0,  565,
      565,  565,  528,  565,  565,  565,  527,  125,  544,  565,
      128,  147,  141,  131,  160,  164,  146,  123,  166,  543,

      180,  176,  199,  200,  203,  202,  201,  204,  211,  207,
      215,  216,  217,  565,  565,  505,  507,  565,  213,  565,
      221,  225,  238,  543,  565,  247,  254,  565,  217,  262,
      223,  565,  565,  236,  247,  224,  244,  274,  254,  266,
      277,  539,  538,  278,  238,  251,  280,  286,  288,  291,
      296,  294,  297,  298,  301,  300,  303,  306,  305,  497,
      494,  297,  336,  311,  309,  565,  299,  339,  565,  289,
      535,  324,  534,  321,  326,  325,  533,  327,  328,  532,
      531,  333,  335,  342,  334,  344,  351,  354,  329,  356,
      357,  358,  360,  530,  355,  485,  478,  366,  371,  519,

      515,  363,  368,  372,  510,  375,  386,  388,  509,  508,
      395,  397,  403,  400,  405,  483,  401,  482,  440,  428,
      406,  462,  461,  410,  460,  459,  458,  457,  455,  411,
      414,  456,  417,  415,  417,  452,  409,    0,  419,  447,
      443,  442,  442,  428,  427,  407,  435,  392,  412,  379,
      226,  411,    0,  138,  116,  413,    0,  565,  565,  415,
      565,  470,  478,  484,  492,  500,  503,  504,  511,  515,
      519,  522,  525
    } ;

static const flex_int16_t yy_def[274] =
    {   0,
      261,    1,  261,  261,  261,  261,  261,  262,  261,  261,
      261,  263,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  264,  261,
      261,  261,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  261,  261,
      261,  261,  261,  262,  261,  262,  261,  261,  261,  261,
      261,  261,  263,  263,  261,  261,  261,  261,  261,  261,
      261,  265,  266,  261,  261,  261,  261,  261,  267,  261,
      261,  261,  261,  261,  261,  261,  261,  262,  264,  261,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  261,  261,  261,  261,  261,  261,  261,
      265,  265,  265,  266,  261,  261,  261,  261,  261,  261,
      267,  261,  261,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  261,
      261,  261,  261,  265,  261,  261,  261,  261,  261,  261,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  261,  261,  261,  261,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  261,  261,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  261,  261,  264,  264,  264,  264,  268,  261,  264,
      264,  264,  269,  270,  271,  272,  269,  261,  270,  261,
      271,  261,  273,  261,  261,  261,  273,  261,  261,  261,
        0,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261
    } ;

static const flex_int16_t yy_nxt[631] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   29,   29,   39,   29,   40,   41,   29,
       29,   42,   43,   44,   45,   46,   47,   48,   29,   29,
       29,   49,   50,   51,   52,   55,   57,   59,   60,   61,
       66,   58,   72,   68,   71,   71,   75,   73,   76,   76,
       67,   69,   70,   74,   62,   86,   87,   77,   88,   81,
       78,   78,   88,   88,   56,   75,   88,   76,   76,   88,

       88,   77,   82,   88,   83,   84,   77,   78,   88,   78,
       78,   79,   88,   88,   88,   78,   88,   88,   55,   88,
       77,   88,  122,   88,  261,  103,   78,  114,  261,  118,
       55,   63,  123,  261,   78,   93,  261,   79,   91,   92,
      259,   94,   96,  258,   95,   98,  261,   56,   99,  100,
      105,  261,  261,   97,   64,  104,  101,  106,  102,   56,
      113,  111,  107,  108,  112,  261,  115,   71,   71,  261,
      110,  261,  109,  141,  126,  126,  119,  120,  136,  120,
      137,  261,  134,  127,  128,  261,  128,  129,  135,  129,
      119,  120,  130,  130,   78,   78,  120,  127,  128,   75,

      140,   76,   76,  128,  261,  261,  261,  261,  261,  261,
       77,   78,  261,   78,   78,  138,  261,  139,  142,   78,
      261,  261,  261,  122,   77,  144,  162,  122,  162,  261,
       78,  163,  163,  123,  143,  130,  130,  123,   78,  149,
      122,  261,  250,  261,  145,  146,  147,  151,  153,  261,
      123,  150,  261,  170,  170,  164,  261,  148,  155,  261,
      156,  158,  159,  154,  152,  126,  126,  167,  157,  167,
      170,  261,  168,  168,  165,  166,  173,  166,  170,  261,
      130,  130,  261,  261,  172,  261,  171,  181,  165,  166,
      169,  261,  169,  261,  166,  177,  261,  174,  175,  261,

      182,  261,  261,  261,  169,  261,  261,  178,  261,  169,
      261,  261,  176,  122,  179,  163,  163,  168,  168,  170,
      170,  180,  198,  123,  198,  183,  261,  199,  199,  261,
      261,  261,  261,  261,  261,  188,  170,  185,  261,  261,
      261,  184,  191,  186,  170,  187,  194,  261,  193,  261,
      192,  189,  195,  190,  163,  163,  261,  168,  168,  261,
      261,  261,  261,  261,  120,  261,  120,  128,  261,  128,
      200,  202,  203,  261,  213,  201,  209,  261,  120,  204,
      261,  128,  205,  120,  199,  199,  128,  206,  207,  199,
      199,  261,  211,  261,  208,  214,  218,  215,  210,  166,

      261,  166,  261,  217,  212,  261,  261,  216,  261,  222,
      261,  261,  221,  166,  261,  261,  261,  209,  166,  261,
      261,  223,  261,  255,  244,  252,  252,  256,  248,  252,
      252,  260,  260,  260,  260,  226,  254,  225,  246,  227,
      224,  245,  228,  250,  248,  246,  230,  261,  261,  242,
      231,  235,  261,  236,  229,  237,  240,  261,  239,  238,
      261,  234,  261,  261,  261,  261,  261,  261,  233,  241,
       54,   54,   54,   54,   54,   54,   54,   54,   63,   63,
       63,  232,   63,   63,   63,   63,   89,  261,  261,   89,
       89,   89,  121,  121,  121,  121,  121,  121,  121,  121,

      124,  124,  124,  124,  124,  124,  124,  124,  131,  131,
      243,  243,  247,  261,  261,  261,  247,  247,  247,  249,
      261,  249,  249,  251,  261,  251,  251,  253,  253,  253,
      257,  257,  257,  220,  219,  261,  261,  261,  261,  261,
      261,  197,  196,  261,  261,  125,  161,  160,  261,  261,
      133,  132,  125,  117,  116,  261,   90,   88,   85,   80,
       65,   64,   53,  261,    3,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261
    } ;

static const flex_int16_t yy_chk[631] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,   10,   10,   11,
       16,    9,   20,   18,   19,   19,   22,   20,   22,   22,
       16,   18,   18,   20,   11,   27,   27,   22,   33,   25,
       22,   22,   34,   41,    8,   21,   35,   21,   21,   36,

       37,   22,   25,   38,   25,   25,   21,   22,   42,   21,
       21,   21,   39,   40,   43,   22,   45,   46,   54,   47,
       21,   48,   72,   44,   64,   41,   21,   50,   98,   63,
       88,   64,   72,   91,   21,   35,   94,   21,   33,   34,
      255,   35,   37,  254,   36,   38,   93,   54,   38,   39,
       43,   97,   92,   37,   63,   42,   39,   44,   40,   88,
       48,   46,   44,   44,   47,   95,   50,   71,   71,   96,
       45,   99,   44,   98,   75,   75,   71,   71,   93,   71,
       94,  102,   91,   75,   75,  101,   75,   77,   92,   77,
       71,   71,   77,   77,   78,   78,   71,   75,   75,   76,

       97,   76,   76,   75,  103,  104,  107,  106,  105,  108,
       76,   78,  110,   76,   76,   95,  109,   96,   99,   78,
      111,  112,  113,  121,   76,  102,  119,  122,  119,  136,
       76,  119,  119,  121,  101,  129,  129,  122,   76,  106,
      123,  134,  251,  145,  103,  104,  105,  108,  109,  137,
      123,  107,  135,  131,  131,  123,  146,  105,  110,  139,
      111,  112,  113,  109,  108,  126,  126,  127,  111,  127,
      131,  140,  127,  127,  126,  126,  136,  126,  131,  138,
      130,  130,  141,  144,  135,  147,  134,  145,  126,  126,
      130,  148,  130,  149,  126,  139,  150,  137,  137,  152,

      146,  151,  153,  154,  130,  156,  155,  140,  157,  130,
      159,  158,  138,  164,  141,  162,  162,  167,  167,  170,
      170,  144,  165,  164,  165,  147,  174,  165,  165,  172,
      176,  175,  178,  179,  189,  152,  170,  149,  182,  185,
      183,  148,  155,  150,  170,  151,  158,  184,  157,  186,
      156,  153,  159,  154,  163,  163,  187,  168,  168,  188,
      195,  190,  191,  192,  163,  193,  163,  168,  202,  168,
      172,  175,  176,  203,  189,  174,  185,  204,  163,  178,
      206,  168,  179,  163,  198,  198,  168,  182,  183,  199,
      199,  207,  187,  208,  184,  190,  195,  191,  186,  199,

      211,  199,  212,  193,  188,  214,  217,  192,  213,  203,
      215,  221,  202,  199,  237,  224,  230,  206,  199,  231,
      234,  204,  235,  250,  239,  246,  246,  252,  249,  252,
      252,  256,  256,  260,  260,  211,  248,  208,  247,  212,
      207,  239,  213,  245,  244,  243,  215,  242,  241,  237,
      217,  224,  240,  230,  214,  231,  234,  236,  233,  232,
      229,  221,  228,  227,  226,  225,  223,  222,  220,  235,
      262,  262,  262,  262,  262,  262,  262,  262,  263,  263,
      263,  219,  263,  263,  263,  263,  264,  218,  216,  264,
      264,  264,  265,  265,  265,  265,  265,  265,  265,  265,

      266,  266,  266,  266,  266,  266,  266,  266,  267,  267,
      268,  268,  269,  210,  209,  205,  269,  269,  269,  270,
      201,  270,  270,  271,  200,  271,  271,  272,  272,  272,
      273,  273,  273,  197,  196,  194,  181,  180,  177,  173,
      171,  161,  160,  143,  142,  124,  117,  116,  100,   89,
       87,   83,   73,   58,   57,   56,   32,   29,   26,   23,
       15,   12,    7,    3,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.l"
#line 9 "parser.l"
//int yylineno = 1;
char datatype[100] = "dummy";
int tl;
int scope_val = 0;
static int scope = 0;
char next;
int initialised=0;
int get_scope();
#include <stdio.h>
#include <string.h> 

typedef struct stack
{
	int val;
	struct stack* next;
}stack;
stack* scope_stk;



#line 690 "lex.yy.c"
#line 691 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 31 "parser.l"

#line 910 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 565 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 32 "parser.l"
{ yylineno++; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 34 "parser.l"
{ printf("single line comment\n");}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 35 "parser.l"
{printf("multi line comment\n");};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "parser.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "parser.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "parser.l"
{ return DEFINE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "parser.l"
{ return DEFINE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "parser.l"
{ return DEFINE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "parser.l"
{  insertToConstTable(yytext, yylineno, "INT"); return CONSTANT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 48 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "parser.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 53 "parser.l"
{  insertToConstTable(yytext, yylineno, "STRING"); return STRING_LITERAL; } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "parser.l"
{  return PTR_OP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "parser.l"
{  return INC_OP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "parser.l"
{  return DEC_OP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "parser.l"
{  return LEFT_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "parser.l"
{  return RIGHT_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "parser.l"
{  return LE_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "parser.l"
{  return GE_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "parser.l"
{  return EQ_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "parser.l"
{  return NE_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "parser.l"
{  return AND_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "parser.l"
{  return OR_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "parser.l"
{  return MUL_ASSIGN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "parser.l"
{  return DIV_ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "parser.l"
{  return MOD_ASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "parser.l"
{  return ADD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "parser.l"
{  return SUB_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "parser.l"
{  return LEFT_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "parser.l"
{  return RIGHT_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "parser.l"
{  return AND_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "parser.l"
{  return XOR_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "parser.l"
{  return OR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "parser.l"
{ return AUTO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "parser.l"
{ return BREAK; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "parser.l"
{ return CHAR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "parser.l"
{ return CONST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "parser.l"
{ return CONTINUE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "parser.l"
{ return DO; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "parser.l"
{ return DOUBLE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "parser.l"
{ return ELSE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "parser.l"
{ return EXTERN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "parser.l"
{ strcpy(datatype, "FLOAT"); tl = yylineno; return FLOAT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "parser.l"
{ return FOR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "parser.l"
{ return IF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "parser.l"
{ strcpy(datatype, "INT"); tl = yylineno; return INT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "parser.l"
{ return LONG; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "parser.l"
{ return REGISTER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "parser.l"
{ return RETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "parser.l"
{ return SHORT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "parser.l"
{ return SIGNED; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "parser.l"
{ return SIZEOF; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "parser.l"
{ return STATIC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "parser.l"
{ return STRUCT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "parser.l"
{ return TYPEDEF; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "parser.l"
{ return UNION; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "parser.l"
{ return UNSIGNED; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "parser.l"
{ return VOID; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "parser.l"
{ return WHILE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "parser.l"
{  strcpy(datatype, "dummy"); return(';'); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "parser.l"
{  	scope++;
				//initState();
				push(scope);
				return('{'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "parser.l"
{  
				pop();
				return('}'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "parser.l"
{  return(','); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "parser.l"
{  return(':'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "parser.l"
{  return('='); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "parser.l"
{  return('('); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "parser.l"
{  return(')'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "parser.l"
{  return('['); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "parser.l"
{  return(']'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "parser.l"
{  return('.'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "parser.l"
{  return('&'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "parser.l"
{  return('!'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "parser.l"
{  return('~'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "parser.l"
{  return('-'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "parser.l"
{  return('+'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "parser.l"
{  return('*'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 127 "parser.l"
{  return('/'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 128 "parser.l"
{  return('%'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 129 "parser.l"
{  return('<'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "parser.l"
{  return('>'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "parser.l"
{  return('^'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "parser.l"
{  return('|'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "parser.l"
{  return('?'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "parser.l"
{  return IDENTIFIER; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 135 "parser.l"
{ return IDENTIFIER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "parser.l"
{  
						if(strcmp(datatype, "dummy")==0)
							return IDENTIFIER;
						else 
						{
							scope_val = get_scope();
							insertToHash(yytext,datatype,yylineno,scope_val);
							return IDENTIFIER; 
						}
					}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 146 "parser.l"
{  }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 147 "parser.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 148 "parser.l"
ECHO;
	YY_BREAK
#line 1457 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 261);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 148 "parser.l"




void push(int scope)
{
	stack *new = NULL;
	new = (stack*)malloc(sizeof(stack));
	new->val = scope;
	new->next = scope_stk;
	scope_stk = new;
}

void pop()
{
	stack * temp = scope_stk;
	scope_stk = temp->next;
	free(temp);
}

int get_scope()
{
	return scope_stk->val;
}

struct cnode
{
	char num[50];
	int lno;
	char type[20];
};
struct cnode ctable[100];
int ccount = 0;

void initState(){
	printf("called\n");
	if(initialised==0){
		scope_stk = (stack*)malloc(sizeof(stack));
		scope_stk->val = 0;
		scope_stk->next = NULL;
		initialised=1;
	}
	
	
}

void insertToConstTable(char *num, int l, char *type)
{
	strcpy(ctable[ccount].num, num);
	strcpy(ctable[ccount].type, type);
	ctable[ccount].lno = l;
	ccount++;
}

struct node
{
	char token[100];
    	char attr[100];
    	int line;
    	int scope;
	struct node *next;
};

struct hash
{
	struct node *head;
	int hash_count;
};

struct hash hashTable[1000];
int hc = 1000;

struct node * createNode(char *token, char *attr, int l, int scope)
{
	struct node *newnode;
	newnode = (struct node *) malloc(sizeof(struct node));
	strcpy(newnode->token, token);
	strcpy(newnode->attr, attr);
	newnode->line = l; 
	newnode->scope = scope;
	newnode->next = NULL;
	return newnode;
}

int hashIndex(char *token)
{
	int hi=0;
	int l,i;
	for(i=0;token[i]!='\0';i++)
	{
		hi = hi + (int)token[i];
	}
	hi = hi%hc;
	return hi;
}

void insertToHash(char *token, char *attr, int l, int scope)
{
	int flag=0;
	int hi;
	hi = hashIndex(token);
	struct node *newnode = createNode(token, attr, l, scope);
	if (hashTable[hi].head==NULL)
	{
		hashTable[hi].head = newnode;
	        hashTable[hi].hash_count = 1;
	        return;
	}
	struct node *myNode;
    	myNode = hashTable[hi].head;
	while (myNode != NULL)
    	{
        	if (strcmp(myNode->token, token)==0)
        	{
            		flag = 1;
            		if(strcmp(myNode->attr, attr)!=0)
            		{
            			strcpy(myNode->attr, attr);
            		}
            		break;
        	}
        	myNode = myNode->next;
    	}
	if(!flag)
	{
		newnode->next = (hashTable[hi].head);
		hashTable[hi].head = newnode;
		hashTable[hi].hash_count++;
	}
	return;
}

char* getvalue(int line, char* type)
{
	int i=0;
	if(strcmp(type, "PROCEDURE") == 0)
		return "";
	while(i<ccount)
	{
		if(line == ctable[i].lno)
		{
			if(strcmp(type, ctable[i].type) == 0)
				return ctable[i].num;
		}
		i++;
	}
	return "";
}

void display()
{
    	struct node *myNode;
    	char *val;
    	int i,j, k=1;
    	printf("\nSymbol Table\n");
    	printf("\nToken \t\t|\tToken Type \t\t|\tLine no.\t\t|\tValue\t\t|\tScope\t\n");
    	for (i = 0; i < hc; i++)
    	{
        	if (hashTable[i].hash_count == 0)
            		continue;
        	myNode = hashTable[i].head;
        	if (!myNode)
            		continue;
        	while (myNode != NULL)
        	{
            		
            		printf("%s\t\t\t", myNode->token);
            		printf("%s\t\t\t", myNode->attr);
            		val = getvalue(myNode->line, myNode->attr);
            		if(i!=0)
            		{
	            		printf("\t%d\t\t",myNode->line);
	            		printf("\t\t%s",val);
	            		printf("\t\t\t%d",myNode->scope);
            		}
            		printf("\n");
            		myNode = myNode->next;
        	}
	}
   	return;
}

yywrap()
{
	return(1);
}

